---
- name: Set up pihole
  hosts: pihole
  gather_facts: no # Gather facts after SSH juggle, in case we can't connect yet
  become: yes

  pre_tasks:
    - ansible.builtin.import_tasks: tasks/shared.yml
      tags: "always"

  roles:
    - role: common
      tags: "common"
    - role: geerlingguy.security
      tags: "security"
    - role: geerlingguy.pip
      tags: "pip"
    - role: geerlingguy.docker
      tags: "docker"
    - role: pihole
      tags:
        - "pihole"
        - "containers"
