---
- name: Set up pihole
  hosts: pihole

  pre_tasks:
    - name: Juggle SSH Ports
      ansible.builtin.import_tasks: tasks/juggle_ssh_port.yml
      tags:
        - always
        - port

  gather_facts: yes
  become: yes

  roles:
    - role: system
      tags: "system"
    - role: geerlingguy.security
      tags: "security"
    - role: pihole
      tags: "pihole"
