---
- name: SSH Port Juggle | Try connecting via SSH
  wait_for_connection:
    timeout: 5
  ignore_errors: true
  register: _ssh_port_result

- name: SSH Port Juggle | Set ansible_ssh_port to default 22
  set_fact:
    original_ssh_port: "{{ ansible_ssh_port }}"
    ansible_ssh_port: "22"
  when:
    - _ssh_port_result is failed

- name: SSH Port Juggle | Try connecting with default port
  wait_for_connection:
    timeout: 5
  ignore_errors: true
  register: _ssh_port_default_result
  when:
    - _ssh_port_result is failed

- name: SSH Port Juggle | Set ansible_user to root
  set_fact:
    original_user: "{{ ansible_user }}"
    ansible_user: "root"
  when:
    - _ssh_port_result is failed
    - _ssh_port_default_result is failed

- name: SSH Port Juggle | Try connecting with root user
  wait_for_connection:
    timeout: 5
  ignore_errors: true
  register: _ssh_port_root_result
  when:
    - _ssh_port_result is failed
    - _ssh_port_default_result is failed

- name: SSH Port Juggle | Fail
  fail:
    msg: "Unable to SSH with port {{ original_ssh_port }}, port 22, or the root user"
  when:
    - _ssh_port_result is failed
    - _ssh_port_default_result is failed
    - _ssh_port_root_result is failed
