---
ansible_connection: ssh

# SSH port to set
security_ssh_port: 50
ansible_ssh_port: 50

ansible_user: "{{ username }}"
password: "{{ vault_ansible_password }}"

traefik_username: "{{ vault_traefik_username }}"
traefik_password: "{{ vault_traefik_password }}"

timezone: "Australia/Brisbane"

shell: /bin/bash
ssh_public_key: id_ed25519

base_domain: local.lachie.xyz

# geerlingguy.security
security_sudoers_passwordless: ["{{ username }}"]
security_autoupdate_enabled: true
security_autoupdate_reboot: true
security_autoupdate_reboot_time: "04:00"
