---
ansible_connection: ssh
ansible_ssh_port: 22

ansible_user: administrator
username: "{{ ansible_user }}"
password: "{{ vault_ansible_password }}"

timezone: "Australia/Brisbane"

shell: /bin/bash
ssh_public_key: id_ed25519

# geerlingguy.security
security_ssh_port: "{{ ansible_ssh_port }}"

security_sudoers_passwordless: ["{{ username }}"]
security_autoupdate_enabled: true
security_autoupdate_reboot: true
security_autoupdate_reboot_time: "04:00"
