---
- name: Update and upgrade packages
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  ansible.builtin.reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Install essential packages
  package:
    name:
      - vim
      - speedtest-cli
      - curl
    state: present
# - name: Update DNS server to point to pihole
#   lineinfile:
#     dest: "/etc/systemd/resolved.conf"
#     regexp: "{{ item.regexp }}"
#     line: "{{ item.line }}"
#     state: present
#   loop:
#     - regexp: "^DNS="
#       line: "DNS={{ pihole_ip }}"
#     - regexp: "^FallbackDNS="
#       line: "FallbackDNS=1.1.1.1"
