---
- name: Update and upgrade packages
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Install essential packages
  package:
    name:
      - vim
      - speedtest-cli
    state: present

- name: Install starship prompt
  community.general.snap:
    name:
      - starship

- name: Add starship prompt to bashrc
  lineinfile:
    dest: "/home/{{ username }}/.bashrc"
    regexp: '^eval "\$\(starship'
    line: 'eval "$(starship init bash)"'
    state: present
