---
- name: Set the name of a sudo group
  set_fact:
    sudo_group: sudo

- name: Ensure all necessary groups are created
  group:
    name: "{{ item }}"
  loop:
    - docker
    - "{{ username }}"

- name: Create a login user
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    groups:
      - "{{ sudo_group }}"
      - docker
      - users
    append: true

- name: "Allow group to have passwordless sudo: '{{ sudo_group }}'"
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%{{ sudo_group }}"
    line: "%{{ sudo_group }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Chmod the user home directory
  file:
    path: "/home/{{ username }}"
    state: directory
    recurse: yes
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Copy public SSH key
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/{{ ssh_public_key }}.pub') }}"

- name: Suppress login message (hushlogin)
  copy:
    content: ""
    dest: "/home/{{ username }}/.hushlogin"
    force: false
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
