---
# --------------------------- IP/Port Mappings ---------------------------

homepage_port: 3000

plex_port: 32400

jellyfin_port: 8096

tautulli_port: 8181
radarr_port: 7878
sonarr_port: 8989
bazarr_port: 6767

prowlarr_port: 9696
overseerr_port: 5055

qbittorrent_port: 8282
qbittorrent_privoxy_port: 8118

speedtest_port: 8765

npm_web_port: 81

# --------------------------- Homepage Credentials ---------------------------

homepage_base_url: "{{ ansible_host }}"

tautulli_api_key: "{{ vault_tautulli_api_key }}"
radarr_api_key: "{{ vault_radarr_api_key }}"
sonarr_api_key: "{{ vault_sonarr_api_key }}"
jellyfin_api_key: "{{ vault_jellyfin_api_key }}"

prowlarr_api_key: "{{ vault_prowlarr_api_key }}"
overseerr_api_key: "{{ vault_overseerr_api_key }}"

bazarr_api_key: "{{ vault_bazarr_api_key }}"

qbittorrent_username: "{{ vault_qbittorrent_username }}"
qbittorrent_password: "{{ vault_qbittorrent_password }}"

# Traefik
traefik_users_file: /mnt/config/traefik/users

cf_api_email: "{{ vault_cf_api_email }}"
cf_dns_api_token: "{{ vault_cf_dns_api_token }}"

# --------------------------- File/dir locations ---------------------------

data_root: "/mnt/data"

docker_compose_dir: "/home/{{ username }}/docker"
docker_config_dir: "/mnt/config"

docker_stacks:
  - networking
  - media-management
  - media-server
  - monitoring
