---
- name: Get user info
  ansible.builtin.getent:
    key: "{{ username }}"
    database: passwd

- name: Verify docker directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  loop:
    - "{{ docker_compose_dir }}"
    - "{{ docker_config_dir }}"

- name: Verify docker-compose directories exist
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  loop: "{{ docker_stacks }}"

# TODO: Speed this up? Takes a long time
- name: Copy docker config files
  ansible.builtin.copy:
    src: "docker-config/"
    dest: "{{ docker_config_dir }}/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Create docker proxy network
  community.docker.docker_network:
    name: media-proxy

- name: Copy docker-compose files
  ansible.builtin.template:
    src: "{{ item }}-docker-compose.yml.j2"
    dest: "{{ docker_compose_dir }}/{{ item }}/docker-compose.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  loop: "{{ docker_stacks }}"
  register: docker_compose_copy_result
  notify: Restart docker compose stacks
