---
- name: "Sync docker compose files"
  when: docker_stacks is defined or docker_services is defined
  block:
    - name: Get user info
      getent:
        key: "{{ username }}"
        database: passwd

    - name: Install Python and python3-pip
      package:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install docker module for Python
      pip:
        name:
          - docker
          - docker-compose

    - name: Verify docker directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
      loop:
        - "{{ docker_compose_dir }}"
        - "{{ docker_config_dir }}"

    - name: Copy docker-compose files
      template:
        src: "./docker/{{ item }}/docker-compose.yml.j2"
        dest: "{{ docker_compose_dir}}/{{ item }}/docker.compose.yml"
      loop: "{{ docker_stacks }}"

    - name: Check docker config exists
      stat:
        path: "./docker/{{ item }}/config/"
      register: config_dir
      loop: "{{ docker_stacks }}"

    - name: Copy docker config files
      copy:
        src: "{{ item.item }}"
        dest: "{{ docker_config_dir }}/"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
      when: item.stat.exists
      loop: "{{ config_dir.results }}"

    - name: Docker-compose up
      community.docker.docker_compose:
        project_src: "{{ docker_compose_dir }}/{{ item }}"
      loop: "{{ docker_stacks }}"
