---
- name: "Sync docker compose files"
  when: docker_stacks is defined or docker_services is defined
  block:
    - name: Get user info
      ansible.builtin.getent:
        key: "{{ username }}"
        database: passwd

    - name: Install Python and python3-pip
      ansible.builtin.package:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install docker module for Python
      ansible.builtin.pip:
        name:
          - docker
          - docker-compose

    # TODO: Combine into one task
    - name: Verify docker directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
      loop:
        - "{{ docker_compose_dir }}"
        - "{{ docker_config_dir }}"

    - name: Verify docker-compose directories exist
      ansible.builtin.file:
        path: "{{ docker_compose_dir }}/{{ item }}"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
      loop: "{{ docker_stacks }}"

    - name: Copy docker-compose files
      ansible.builtin.template:
        src: "files/{{ item }}/docker-compose.yml.j2"
        dest: "{{ docker_compose_dir }}/{{ item }}/docker-compose.yml"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
      loop: "{{ docker_stacks }}"

    - name: Copy docker config files
      ansible.builtin.copy:
        src: "files/config/"
        dest: "{{ docker_config_dir }}/"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755

    - name: Docker-compose up
      community.docker.docker_compose:
        project_src: "{{ docker_compose_dir }}/{{ item }}"
      loop: "{{ docker_stacks }}"
