http:
  routers:
    proxmox:
      entryPoints:
        - https
      rule: Host(`proxmox.local.lachie.xyz`)
      service: proxmox
    pihole:
      entryPoints:
        - https
      rule: Host(`pihole.local.lachie.xyz`)
      service: pihole

  services:
    proxmox:
      loadBalancer:
        servers:
          - url: "https://10.0.0.20:8006"
    pihole:
      loadBalancer:
        servers:
          - url: "http://10.0.0.5"

  middlewares:
    local-ipwhitelist:
      ipWhiteList:
        sourceRange:
          - "10.0.0.0/8"
          - 127.0.0.1/32 # localhost
          - 192.168.1.1/24 # LAN Subnet
    security-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
