---
- name: Update and upgrade packages
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes
  when: ansible_facts.os_family === "Debian"

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  ansible.builtin.reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Install essential packages
  package:
    name: "{{ essential_packages }}"
    state: present
