---
- name: Set self as DNS nameserver
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    state: present
    regexp: "^nameserver 127.0.0.1"
    line: "nameserver 127.0.0.1"
    insertbefore: BOF

- name: Disable systemd
  ansible.builtin.service:
    name: systemd-resolved
    enabled: false
    state: stopped

- name: Ensure target dirs exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  loop:
    - /etc/dnsmasq.d
    - /etc/pihole
    - /home/{{ username }}/pihole

- name: Get DNS overrides from Traefik
  include_tasks: traefik.yml
  when: traefik_hosts is defined
  with_dict: "{{ traefik_hosts }}"
  tags: "traefik"
  args:
    apply:
      tags:
        - "traefik"

- name: Copy dnsmasq config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  loop:
    - src: localnet.conf.j2
      dest: /etc/dnsmasq.d/02-localnet.conf
    - src: pihole-docker-compose.yml.j2
      dest: "/home/{{ username }}/pihole/docker-compose.yml"

- name: Start/update pihole container
  community.docker.docker_compose:
    project_src: "/home/{{ username }}/pihole/"
    build: false
    restarted: true

- name: Check pihole container
  ansible.builtin.uri:
    url: http://localhost/admin
  register: result
  until: result.status == 200
  retries: 5
  delay: 5

- name: Remove old image versions
  docker_prune:
    images: yes
    images_filters:
      dangling: false
