---
# Get rule from routers with provider = "docker"
- name: Add Traefik API url to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    state: present
    regexp: "^{{ item.key }}"
    line: "{{ item.key }} {{ item.value | regex_replace('^https:\/\/(.*)$', '\\1') }}"
  when: item.value is defined

- name: Get rules from Traefik
  ansible.builtin.uri:
    url: '{{ item.value | default("http://{{ item.key }}:8080") }}/api/http/routers'
    user: "{{ traefik_username }}"
    password: "{{ traefik_password }}"
    return_content: true
  register: traefik_routers
  failed_when: traefik_routers.status != 200

- name: Format traefik rules and add to any existing DNS overrides
  ansible.builtin.set_fact:
    dns_overrides: "{{ (dns_overrides | default({})) | combine(new_item) }}"
  vars:
    new_item: "{ '{{ item.key }}': {{ traefik_routers.json \
      | selectattr('provider', '!=', 'internal') \
      | map(attribute='rule') \
      | map('regex_replace', '^Host\\(`(.*)`\\)$', '\\1') \
      + (dns_overrides[item] | default([])) \
      | unique }} }"
